source 'https://rubygems.org'

# Specify your gem's dependencies in cocoapods-zource.gemspec
gemspec

group :development do

  gem 'cocoapods'#, :path => './CocoaPods'
  gem 'xcodeproj'

  gem 'mocha'
  gem 'bacon'
  gem 'mocha-on-bacon'
  gem 'prettybacon'

  gem 'ruby-debug-ide'     
  gem 'debase'
end
